apiVersion: v1
kind: Service
metadata:
  name: config-example
  namespace: uwbdev
spec:
  selector:
    app: config-example
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-example
  namespace: uwbdev
spec:
  selector:
    matchLabels:
      app: config-example
  replicas: 1
  template:
    metadata:
      labels:
        app: config-example
    spec:
      containers:
        - name: config-example
          image: arunmp/config-example:0.0.6-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080