apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: uwb-custom-role
  namespace: uwbdev
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","services","endpoints","namespaces","configmaps","secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uwb-custom-role
  namespace: uwbdev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: uwb-custom-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: uwbdev
