logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: config-example
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      loadbalancer:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health